### ISSUE TITLE
timing limits don't work with pytest-django

### ISSUE THREAD

**Issue by stardust85** [PaesslerAG/django-performance-testing#29]
Hello, I use pytest-django to be able to run tests with pytest runner. Query limits work well, timing doesn't. Pytest is a popular test runner (2500 github stars) and allows for more comfortable asserting (assert 1 < 2 vs. self.assertGreaterThan(2,1))

Please look at possibility of supporting pytest.

```
$ pip freeze | egrep '(test|Django)'
Django==1.11.9
django-performance-testing==0.7.3
pytest==3.2.5
pytest-cov==2.5.1
pytest-django==3.1.2
```

**Comment by kairichard** [comment]
Hi @stardust85 
thanks for reporting the issues with us. 
For timings to work, the lib needs to hijack the default `TestRunner` that comes with django. 
However `pytest-django`  does not use the `TestRunner` and bends the world to make django run under `pytest` see https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/plugin.py. 

ATM we don't plan on supporting `pytest`. IIRC you can use `--durations=N` with `pytest` to at least discover slow tests. 

HTH,
Kai
